# Generated by Django 4.0.10 on 2023-11-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='nomEleve')),
                ('prenom', models.CharField(max_length=50, verbose_name='prenomEleve')),
                ('age', models.IntegerField(verbose_name='age')),
            ],
        ),
    ]
